### ISSUE TITLE
Unable to authenticate - {{baseUrl}}/Login returns 404

### ISSUE THREAD

**Issue by OPVL** [rstefko/eway-crm-php-lib#6]
When attempting to login the curl in the login returns and empty body as the /Login route is not found.

**Has this route been moved?**

### Additional info:
* PHP 7.3
* CURL is enabled
* tested in postman
* tested with example service root url found in these docs
* Does not accept GET or POST (returns 404)
* Account urls tested as `https://free.eway-crm.com/34491/login` & `https://free.eway-crm.com/34491/Login`

### Code Used
```php
<?php
$pageTitle = 'Home';

require_once 'config.php';
require_once 'php-lib-2.1/eway.class.php';
require_once 'sections/header.php';

$contacts;
$companies;

try {
    $eway = new eWayConnector($EWAY_URL, $EWAY_USER, md5($EWAY_PASS), true);
} catch (\Throwable $th) {
    die($th->getMessage());
}
$db = new mysqli($DB_HOST, $DB_USER, $DB_PASS);

if ($db->errno){
    die($db->error);
} else {
    echo "Database Connection established.<br>";
}

try {
    echo ("Attempting to authenticate with eWay: $EWAY_URL, $EWAY_PASS, $EWAY_USER<br>");
    print_r($eway->getCompanies());
} catch (\Throwable $th) {
    die($th->getMessage());
}
?>
```

## Output
![alt text](https://i.imgur.com/iklWDNl.png "Logo Title Text 1")

**Comment by rstefko** [comment]
Hi @OPVL,

the correct full URL is https://free.eway-crm.com/34491/WcfService/Service.svc/LogIn. It works with POST only.

Regards
Roman

**Comment by OPVL** [comment]
Ah is that mentioned in the documentation anywhere just for future reference?
Closing issue as it's a configuration issue.

Thanks to @rstefko

**Comment by rstefko** [comment]
We will prepare some examples on how to call API using Postman.
